export const FETCH_GAMES = 'GAME/FETCH_GAMES';
export const FETCH_GAMES_SUCCESS = 'GAME/FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAIL = 'GAME/FETCH_GAMES_FAIL';

export const REGISTER_GAME = 'GAME/REGISTER_GAME';
export const REGISTER_GAME_SUCCESS = 'GAME/REGISTER_GAME_SUCCESS';
export const REGISTER_GAME_FAIL = 'GAME/REGISTER_GAME_FAIL';
