version: '2'

services:
  game-catalog-api:
    image: back-end
    container_name: game-catalog-api
    ports:
      - "8080:8080"
    depends_on:
      - db-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db-postgres:
    image: 'postgres:13.1-alpine'
    ports:
      - "5433:5432"
    container_name: db-postgres
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  games-catalog-client:
    build: ../front-end/
    ports:
      - "3000:3000"
    depends_on:
      - game-catalog-api