server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://app-database-link:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true

